"""add promotion

Revision ID: cd04d9219502
Revises: 
Create Date: 2022-09-22 17:31:40.132787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd04d9219502'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('promotion', sa.Boolean(), nullable=True))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_column('items', 'promotion')
    # ### end Alembic commands ###
