# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI
defaults:
  run:
    shell: bash
    working-directory: ./natal_delivery
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry
      run: pip install --upgrade pip && pip install poetry

    - name: Install Project
      run: poetry install

    - name: Database Migrations
      run: |
        FLASK_APP=natal_delivery/app.py poetry run flask create db
        FLASK_APP=natal_delivery/app.py poetry run flask db upgrade
    
    - name: Runs tests
      run: poetry run pytest -v
